import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  flex1: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyCenter: { justifyContent: 'center' },
  itemsStart: { alignItems: 'flex-start' },
  itemsEnd: { alignItems: 'flex-end' },
  itemsCenter: { alignItems: 'center' },

  ml1: { marginLeft: 4 },
  ml2: { marginLeft: 8 },
  ml3: { marginLeft: 12 },
  ml4: { marginLeft: 16 },
  mr2: { marginRight: 8 },
  mr3: { marginRight: 12 },
  mr4: { marginRight: 16 },
  mt1: { marginTop: 4 },
  mt3: { marginTop: 12 },
  mt4: { marginTop: 16 },
  mb0: { marginBottom: 0 },
  mb2: { marginBottom: 8 },
  mb4: { marginBottom: 16 },
  mb6: { marginBottom: 24 },
  mb8: { marginBottom: 32 },
  mx1: { marginHorizontal: 4 },
  p2: { padding: 8 },
  pt4: { paddingTop: 16 },

  fontMedium: { fontWeight: '500', color: '#111827' },
  fontBold: { fontWeight: 'bold', color: '#111827' },
  textGrayXs: { fontSize: 12, color: '#9ca3af' },
  textGraySm: { fontSize: 14, color: '#6b7280' },
  textGraySmItalic: { fontSize: 14, color: '#9ca3af', fontStyle: 'italic' },
  textMedium: { fontSize: 14, fontWeight: '500', color: '#111827' },
  textLgBold: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
  textBlueBold: { fontSize: 14, fontWeight: 'bold', color: '#3b82f6' },

  scrollPadding: { paddingHorizontal: 16, paddingTop: 24, paddingBottom: 100 },
  screenTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 24, color: '#111827' },
  screenTitleNoMargin: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12, color: '#111827' },
  emptyText: { color: '#9ca3af', fontSize: 14, marginBottom: 24 },

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    borderColor: '#f3f4f6',
    borderWidth: 1,
  },
  rounded3xl: { borderRadius: 24 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  iconBoxBlue: { padding: 8, backgroundColor: '#eff6ff', borderRadius: 12 },
  iconBoxGray: { padding: 8, backgroundColor: '#f3f4f6', borderRadius: 12 },
  cardCityText: { fontWeight: 'bold', fontSize: 15, color: '#111827' },
  cardDateText: { fontSize: 12, color: '#9ca3af' },

  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  statusBadgeText: { fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },

  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#f9fafb',
    padding: 12,
    borderRadius: 12,
    marginTop: 8,
  },
  detailsCol: { width: '50%', marginBottom: 12 },
  detailsLabel: {
    fontSize: 10,
    color: '#9ca3af',
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  detailsValue: { fontSize: 14, fontWeight: '500', color: '#111827' },

  yellowDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#facc15',
    marginTop: 6,
  },
  descriptionText: { fontSize: 12, color: '#4b5563', marginLeft: 8, flex: 1 },

  mapPlaceholder: {
    height: 180,
    backgroundColor: '#eff6ff',
    borderRadius: 16,
    overflow: 'hidden',
    borderColor: '#e5e7eb',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapCenter: { justifyContent: 'center', alignItems: 'center' },
  mapPing: {
    position: 'absolute',
    width: 48,
    height: 48,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderRadius: 24,
  },
  mapPin: {
    width: 32,
    height: 32,
    backgroundColor: '#3b82f6',
    borderRadius: 16,
    borderWidth: 4,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  mapAttribution: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  mapAttributionText: { fontSize: 10, color: '#9ca3af' },

  btnSmallBlue: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  btnSmallBlueText: { color: 'white', fontSize: 12, fontWeight: '500' },
  btnOrange: {
    backgroundColor: '#fb923c',
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnGreen: {
    backgroundColor: '#22c55e',
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  btnBlue: {
    backgroundColor: '#3b82f6',
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  btnBlueShadow: {
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  btnGray: {
    backgroundColor: '#f3f4f6',
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnLightBlue: {
    backgroundColor: '#eff6ff',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
  },
  btnLightBlueSm: {
    backgroundColor: '#eff6ff',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  btnLightBlueTextSm: { color: '#3b82f6', fontSize: 12, fontWeight: 'bold' },
  btnTextWhite: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  btnTextWhiteLg: { color: 'white', fontWeight: 'bold', fontSize: 16 },
  btnTextBlack: { color: '#111827', fontWeight: 'bold', fontSize: 14 },
  btnLightBlueText: { color: '#3b82f6', fontWeight: 'bold', fontSize: 14 },

  podBox: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  cameraIconBox: {
    width: 48,
    height: 48,
    backgroundColor: '#eff6ff',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  podText: { fontSize: 14, color: '#6b7280', marginBottom: 16 },

  iconBtnBlue: {
    width: 40,
    height: 40,
    backgroundColor: '#3b82f6',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    padding: 4,
    borderRadius: 12,
    marginBottom: 24,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  tabBtnActive: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#6b7280',
    marginLeft: 4,
  },
  tabBtnTextActive: { color: '#111827' },

  darkCard: {
    backgroundColor: '#111827',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  darkCardMap: {
    height: 100,
    backgroundColor: '#1f2937',
    borderRadius: 12,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#374151',
    borderWidth: 1,
  },
  pulseDotWrapper: {
    position: 'relative',
    width: 12,
    height: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pulseDotBg: {
    position: 'absolute',
    width: 24,
    height: 24,
    backgroundColor: '#4ade80',
    borderRadius: 12,
    opacity: 0.4,
  },
  pulseDot: { width: 12, height: 12, backgroundColor: '#4ade80', borderRadius: 6 },
  greenDot: {
    width: 10,
    height: 10,
    backgroundColor: '#22c55e',
    borderRadius: 5,
    marginRight: 8,
  },
  darkCardText: { color: 'white', fontWeight: 'bold' },

  routeDivider: {
    flex: 1,
    marginHorizontal: 16,
    justifyContent: 'center',
    position: 'relative',
  },
  routeDividerLine: { height: 1, backgroundColor: '#e5e7eb', width: '100%' },
  routeDividerIcon: {
    position: 'absolute',
    left: '50%',
    marginLeft: -10,
    backgroundColor: '#fff',
    paddingHorizontal: 4,
  },

  halfCol: { width: '50%', marginBottom: 16 },
  commentBox: {
    backgroundColor: '#f9fafb',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },

  aiBox: {
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
    padding: 16,
    borderRadius: 16,
  },
  aiTitle: { fontWeight: 'bold', color: '#2563eb', fontSize: 16 },
  aiSubtitle: { fontSize: 14, color: '#4b5563', marginBottom: 16 },
  aiInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 12,
    height: 100,
    marginBottom: 16,
    fontSize: 14,
  },

  input: {
    width: '100%',
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    marginBottom: 12,
  },
  inputLarge: {
    width: '100%',
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 14,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  inputLabel: { fontSize: 12, color: '#6b7280', marginBottom: 4, marginLeft: 4 },

  deleteBtnAbs: { position: 'absolute', top: 16, right: 16, padding: 4 },
  plateTag: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  plateTagText: {
    fontSize: 12,
    color: '#6b7280',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  cardFooter: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  avatarOrange: {
    width: 48,
    height: 48,
    backgroundColor: '#ffedd5',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },

  profileAvatarContainer: { position: 'relative' },
  profileAvatarMock: {
    width: 80,
    height: 80,
    backgroundColor: '#991b1b',
    borderRadius: 40,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: { color: 'white', fontSize: 32, fontWeight: 'bold' },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    backgroundColor: '#14b8a6',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: { fontSize: 24, fontWeight: 'bold', marginBottom: 4 },
  ratingBadge: {
    backgroundColor: '#fb923c',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  idTag: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 24,
  },
  idTagText: {
    fontSize: 12,
    color: '#9ca3af',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  companyLogo: {
    width: 48,
    height: 48,
    backgroundColor: '#000',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  companyLogoText: { color: 'white', fontSize: 10 },
  settingsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  settingsItemNoBorder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },

  langContainer: { flex: 1, backgroundColor: '#1e3a8a' },
  langHeader: { flexDirection: 'row', alignItems: 'center', padding: 16 },
  langTitle: { color: 'white', fontSize: 24, fontWeight: 'bold', marginLeft: 16 },
  langContent: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingTop: 24,
  },
  langCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  langCardActive: {
    borderColor: '#3b82f6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  langName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 4,
  },
  langNative: { fontSize: 14, color: '#6b7280' },
  radioCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioCircleActive: { borderColor: '#3b82f6' },
  radioDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#3b82f6' },

  selectMock: {
    width: '100%',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectMockText: { fontSize: 14, color: '#111827' },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  bottomSheetContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '90%',
  },
  bottomSheetHandle: {
    width: 48,
    height: 6,
    backgroundColor: '#d1d5db',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 16,
  },
  bottomSheetTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
    color: '#111827',
  },
  bottomSheetSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 16,
  },
  bottomSheetContent: { paddingHorizontal: 8 },

  toastContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 40,
    alignSelf: 'center',
    backgroundColor: '#1f2937',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 100,
  },
  toastText: { color: 'white', fontWeight: '500', fontSize: 14 },

  devBar: {
    backgroundColor: '#111827',
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  devBarTitle: {
    color: 'white',
    opacity: 0.5,
    fontWeight: 'bold',
    fontSize: 12,
  },
  devBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#374151',
  },
  devBtnActive: { backgroundColor: '#3b82f6' },
  devBtnText: { color: 'white', fontSize: 12 },

  bottomNav: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 10,
  },
  navItem: { alignItems: 'center', width: 64 },
  navItemActive: { transform: [{ translateY: -4 }] },
  navLabel: { fontSize: 10, fontWeight: '500', marginTop: 4 },

  appContainer: { flex: 1, backgroundColor: '#f9fafb' },
});

export default styles;